### ISSUE TITLE
Minor UI bug - When the dropdown list is in the last row of a Table component, the options are hidden

### ISSUE THREAD

**Issue by melohagan** [sj-distributor/budibase-component-dropdown-list#1]
Firstly, great component! Looks to be working well, just noticed this minor visual issue:

![Screenshot 2023-04-04 at 09 09 06](https://user-images.githubusercontent.com/101575380/229729185-896059f0-55d5-4965-9e5f-b1e91c78e49f.png)

**After scrolling:**
![Screenshot 2023-04-04 at 09 09 38](https://user-images.githubusercontent.com/101575380/229729324-fc9c5844-8d77-45b7-a427-c6b19a9a725e.png)

**Comment by OPEN-9** [comment]
Dear @melohagan 

Thank you for bringing this issue to our attention. We have reviewed your feedback and have implemented a solution to address the problem you reported. We have added a button that allows you to choose the direction of the position method, with two properties: bottom and right.

content was unable to exceed the iframe tag due to technical limitations. However, we believe that this new feature will provide a more flexible and user-friendly experience.

Thank you for your patience and understanding. If you have any further questions or concerns, please do not hesitate to contact us.

Best regards
